const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');

test('Age of Civilization houdt spelerkaarten vast, toont details en laat onbetaalbare upgrades inspecteren',()=>{
  const client=fs.readFileSync(path.join(root,'games/civilization/client.js'),'utf8');
  const css=fs.readFileSync(path.join(root,'games/civilization/styles.css'),'utf8');
  assert.match(css,/#gameStage:has\(\.civ-root\)\{[^}]*overflow:hidden!important/);
  assert.match(css,/\.civ-grid \{[^}]*grid-template-columns: repeat\(6, minmax\(0,1fr\)\)/);
  assert.match(css,/@media\(min-height:720px\)\{[\s\S]*?\.civ-grid\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)/);
  assert.match(css,/@media\(max-width:760px\)\{[\s\S]*?\.civ-grid\{grid-template-columns:repeat\(3,minmax\(0,1fr\)\)\}/);
  assert.match(css,/\.civ-modal-backdrop\{position:absolute;[^}]*place-items:center/);
  assert.match(client,/function showCivModal/);
  assert.match(client,/function renderLobbyOptions/);
  assert.match(client,/\['classic','Classic'/);
  assert.match(client,/\['deathmatch','Deathmatch'/);
  assert.match(client,/confirmLabel:'Bouw'/);
  assert.match(client,/eyebrow:'Jouw stad'/);
  assert.match(client,/eyebrow:'Vast gebouw'/);
  assert.match(client,/function statBadges/);
  assert.match(css,/\.civ-player-chip \{[\s\S]*?flex: 0 0 92px; width:92px/);
  assert.match(css,/\.civ-chip-name \{[^}]*text-overflow:ellipsis/);
  assert.match(client,/eyebrow:'Speler'/);
  assert.match(client,/function playerDetails/);
  assert.match(client,/civ-player-details/);
  assert.match(client,/if\(!afford\)node\.classList\.add\('unaffordable'\)/);
  assert.match(client,/confirmDisabled:!afford/);
  assert.match(client,/Kost \$\{cost\} goud/);
  assert.match(client,/function statGainText\(\{attack=0,defence=0,income=0\}\)/);
  assert.match(client,/\+\$\{attack\} Attack/);
  assert.match(client,/Niveau \$\{tile\.level\} → \$\{tile\.level\+1\}/);
  assert.match(client,/confirmDisabled:!canBuild/);
  assert.match(client,/function showCombatModal/);
  assert.match(client,/civ-combat-table/);
  assert.match(client,/\['Speler','ATK','DEF','Valt aan','Schade'\]/);
  assert.match(client,/confirmLabel:'Doorgaan',required:true/);
  assert.match(client,/badges:statBadges\(tile,\{next:true\}\)/);
  assert.match(client,/badges:statBadges\(card\)/);
  assert.match(css,/\.civ-chip-leader \{[^}]*text-overflow:ellipsis/);
  assert.match(css,/\.civ-modal-actions:has\(\.civ-modal-secondary\) \.civ-modal-confirm\{grid-column:1\/-1/);
  assert.doesNotMatch(client,/civ-detail-slot/);
});

