export const roomOptions={bodyClass:'elements-mode'};
const META={fire:{label:'FIRE',symbol:'△'},water:{label:'WATER',symbol:'≈'},earth:{label:'EARTH',symbol:'◇'},air:{label:'AIR',symbol:'≋'}};
let animation=null;
function svgEl(tag,attrs={}){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n}
function pathPoint(path,t){if(!path?.length)return null;const scaled=Math.max(0,Math.min(1,t))*(path.length-1),i=Math.min(path.length-2,Math.floor(scaled)),f=scaled-i,a=path[i],b=path[i+1]||a;return{x:a.x+(b.x-a.x)*f,y:a.y+(b.y-a.y)*f,gone:t>=1?b.gone:a.gone}}
function stoneNode(stone,extra=''){const m=META[stone.element],g=svgEl('g',{class:`elements-stone element-${stone.element} ${extra}`,'data-stone-id':stone.id});g.append(svgEl('circle',{cx:stone.x+4,cy:stone.y+7,r:25,class:'elements-stone-shadow'}),svgEl('circle',{cx:stone.x,cy:stone.y,r:24,class:'elements-stone-disc'}));const mark=svgEl('text',{x:stone.x,y:stone.y+8,class:'elements-stone-symbol'});mark.textContent=m.symbol;g.append(mark);return g}
function setStone(node,p){if(!node||!p)return;const circles=node.querySelectorAll('circle'),text=node.querySelector('text');circles[0].setAttribute('cx',p.x+4);circles[0].setAttribute('cy',p.y+7);circles[1].setAttribute('cx',p.x);circles[1].setAttribute('cy',p.y);text.setAttribute('x',p.x);text.setAttribute('y',p.y+8);node.classList.toggle('gone',Boolean(p.gone))}

export function render({room,game,els,E,action,sound,state}){
  const me=game.players.find(p=>p.id===room.meId),turn=game.players.find(p=>p.id===game.turnPlayerId);
  const screen=E('div','elements-screen');
  const hud=E('div','elements-hud');
  const heading=E('div','elements-heading');heading.append(E('span','elements-brand','ELEMENTS ARENA'),E('strong','',`END ${game.end} / 2`));hud.append(heading);
  const players=E('div',`elements-players count-${game.players.length}`);
  for(const p of game.players){const card=E('div',`elements-player${p.id===game.turnPlayerId?' active':''}${p.id===room.meId?' me':''}`);const top=E('div','elements-player-top');top.append(E('strong','',p.name),E('b','',`${p.totalPoints} pt`));const stock=E('div','elements-public-stock');for(const element of ['fire','water','earth','air']){const chip=E('span',`element-${element}${p.remaining.includes(element)?'':' used'}`,META[element].symbol);chip.title=`${META[element].label}${p.remaining.includes(element)?'':' gebruikt'}`;stock.append(chip)}card.append(top,stock);players.append(card)}hud.append(players);screen.append(hud);

  const arenaWrap=E('div','elements-arena-wrap');
  const svg=svgEl('svg',{viewBox:'0 0 900 900',class:'elements-arena',role:'img','aria-label':'Ronde Elements Arena met vier scorezones'});
  const defs=svgEl('defs');defs.innerHTML='<filter id="arenaGrain"><feTurbulence baseFrequency=".55" numOctaves="2" seed="8" result="noise"/><feBlend in="SourceGraphic" in2="noise" mode="soft-light"/></filter>';
  svg.append(defs,svgEl('circle',{cx:450,cy:458,r:414,class:'elements-arena-shadow'}),svgEl('circle',{cx:450,cy:450,r:410,class:'elements-zone zone-outer'}),svgEl('circle',{cx:450,cy:450,r:270,class:'elements-zone zone-middle'}),svgEl('circle',{cx:450,cy:450,r:155,class:'elements-zone zone-inner'}),svgEl('circle',{cx:450,cy:450,r:64,class:'elements-zone zone-nexus'}));
  for(const [r,label,pts]of [[340,'OUTER',1],[212,'MIDDLE',2],[109,'INNER',3],[0,'NEXUS',5]]){const y=r?450-r+19:455,tag=svgEl('text',{x:450,y,class:`elements-zone-label ${r?'':'nexus-label'}`});tag.textContent=`${label} · ${pts}`;svg.append(tag)}
  svg.append(svgEl('circle',{cx:450,cy:450,r:395,class:'elements-etch'}));
  const nodes=new Map(),pendingIds=new Set(Object.keys(game.pendingShot?.paths||{}));
  for(const stone of game.stones){const node=stoneNode(stone);svg.append(node);nodes.set(stone.id,node)}
  if(game.launch&&game.canShoot&&me){const preview={id:'launch',playerId:me.id,element:me.remaining[0],x:game.launch.x,y:game.launch.y};const node=stoneNode(preview,'launch-stone');svg.append(node);nodes.set('launch',node)}
  if(game.pendingShot){for(const[id,path]of Object.entries(game.pendingShot.paths)){if(nodes.has(id))continue;const first=path[0],stone=game.stones.find(s=>s.id===id)||{id,element:id===game.pendingShot.id?game.pendingShot.element:'air',x:first.x,y:first.y};const node=stoneNode(stone);svg.append(node);nodes.set(id,node)}}
  const aim=svgEl('g',{class:'elements-aim hidden'}),line=svgEl('line',{class:'elements-aim-line'}),target=svgEl('circle',{r:18,class:'elements-target'}),pull=svgEl('line',{class:'elements-pull-line'});aim.append(line,target,pull);svg.append(aim);arenaWrap.append(svg);screen.append(arenaWrap);

  let status=game.gameOver?'Match afgelopen.':game.phase==='between'?'De stenen worden opnieuw klaargelegd…':game.pendingShot?`${game.pendingShot.playerName} speelt ${META[game.pendingShot.element].label}…`:game.canShoot?'Kies een steen en sleep achteruit om te mikken.':`${turn?.name||'Speler'} is aan de beurt.`;
  const bottom=E('div','elements-bottom'),tray=E('div','elements-tray');let selected=me?.remaining?.[0]||null;
  const updateSelection=()=>{tray.querySelectorAll('button').forEach(b=>b.classList.toggle('selected',b.dataset.element===selected));const launch=nodes.get('launch');if(launch){launch.className.baseVal=`elements-stone element-${selected} launch-stone`;launch.querySelector('text').textContent=META[selected].symbol}};
  for(const element of ['fire','water','earth','air']){const available=Boolean(me?.remaining.includes(element)),button=E('button',`elements-choice element-${element}${available?'':' used'}`);button.type='button';button.dataset.element=element;button.disabled=!game.canShoot||!available;button.append(E('span','elements-choice-symbol',META[element].symbol),E('small','',META[element].label));button.onclick=()=>{selected=element;updateSelection()};tray.append(button)}
  const statusNode=E('div','elements-status',status),power=E('div','elements-power');power.append(E('span',''));bottom.append(tray,statusNode,power);if(game.lastEndSummary)bottom.append(E('small','elements-end-summary',game.lastEndSummary));screen.append(bottom);els.gameStage.append(screen);updateSelection();

  if(game.pendingShot){if(!animation||animation.id!==game.pendingShot.id)animation={id:game.pendingShot.id,start:performance.now()};const a=animation;const frame=now=>{if(!svg.isConnected||state.room?.gameState?.pendingShot?.id!==a.id)return;const t=Math.min(1,(now-a.start)/Math.max(1,game.pendingShot.durationMs));for(const[id,path]of Object.entries(game.pendingShot.paths))setStone(nodes.get(id),pathPoint(path,t));if(t<1)requestAnimationFrame(frame)};requestAnimationFrame(frame)}else animation=null;

  if(game.canShoot&&game.launch&&selected){let dragging=false,pointerId=null,start=null,last=null;const point=event=>{const r=svg.getBoundingClientRect();return{x:(event.clientX-r.left)/r.width*900,y:(event.clientY-r.top)/r.height*900}};const update=p=>{if(!start)return null;const dx=start.x-p.x,dy=start.y-p.y,d=Math.hypot(dx,dy);if(d<3){aim.classList.add('hidden');power.firstChild.style.width='0';return null}const amount=Math.min(1,d/210),ux=dx/d,uy=dy/d,end={x:game.launch.x+ux*(75+amount*175),y:game.launch.y+uy*(75+amount*175)};aim.classList.remove('hidden');line.setAttribute('x1',game.launch.x);line.setAttribute('y1',game.launch.y);line.setAttribute('x2',end.x);line.setAttribute('y2',end.y);target.setAttribute('cx',end.x);target.setAttribute('cy',end.y);pull.setAttribute('x1',start.x);pull.setAttribute('y1',start.y);pull.setAttribute('x2',p.x);pull.setAttribute('y2',p.y);power.firstChild.style.width=`${Math.round(amount*100)}%`;return{angle:Math.atan2(uy,ux),power:amount}};
    svg.addEventListener('pointerdown',event=>{dragging=true;pointerId=event.pointerId;start=point(event);last=null;svg.setPointerCapture?.(pointerId);event.preventDefault()});svg.addEventListener('pointermove',event=>{if(!dragging||event.pointerId!==pointerId)return;last=update(point(event));event.preventDefault()});const finish=event=>{if(!dragging||event.pointerId!==pointerId)return;last=update(point(event))||last;dragging=false;aim.classList.add('hidden');power.firstChild.style.width='0';if(last?.power>=.06&&selected){sound('card');action('shoot',{element:selected,...last})}event.preventDefault()};svg.addEventListener('pointerup',finish);svg.addEventListener('pointercancel',()=>{dragging=false;aim.classList.add('hidden');power.firstChild.style.width='0'})
  }
}

export function metric({player}){return{text:`${player.totalPoints} pt`,score:Number(player.totalPoints||0)}}
export function presentResult({game}){const w=game.players.filter(p=>game.winnerIds?.includes(p.id));return w.length===1?{title:w[0].name,copy:'claimt de Nexus.'}:{title:'Gelijkspel',copy:'De arena blijft verdeeld.'}}
export function isWinner({game,myId}){return game.winnerIds?.length===1&&game.winnerIds[0]===myId}
